defmodule Mcp.Repo.TenantMigrations.CreateUnderwritingDocuments do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop constraint(:underwriting_checks, "underwriting_checks_document_id_fkey")

    alter table(:underwriting_checks, prefix: prefix()) do
      modify :document_id,
             references(:underwriting_documents,
               column: :id,
               name: "underwriting_checks_document_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end
  end

  def down do
    drop constraint(:underwriting_checks, "underwriting_checks_document_id_fkey")

    alter table(:underwriting_checks, prefix: prefix()) do
      modify :document_id,
             references(:underwriting_documents,
               column: :id,
               name: "underwriting_checks_document_id_fkey",
               type: :uuid,
               prefix: prefix()
             )
    end
  end
end
