Code.put_compiler_option(:ignore_module_conflict, true)
defmodule Mcp.Repo.TenantMigrations.CreateUnderwritingAndFixFinance do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:customers, prefix: prefix()) do
      modify :status, :text, null: false
    end
  end

  def down do
    alter table(:customers, prefix: prefix()) do
      modify :status, :text, null: true
    end
  end
end
