defmodule Mcp.Repo.TenantMigrations.CreateTeams do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:underwriting_reviews, prefix: prefix()) do
      add :reviewer_id,
          references(:users,
            column: :id,
            name: "underwriting_reviews_reviewer_id_fkey",
            type: :uuid,
            prefix: "platform"
          ),
          null: false
    end
  end

  def down do
    drop constraint(:underwriting_reviews, "underwriting_reviews_reviewer_id_fkey")

    alter table(:underwriting_reviews, prefix: prefix()) do
      remove :reviewer_id
    end
  end
end
