defmodule Mcp.Repo.TenantMigrations.AddApplicationToRiskAssessment do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:risk_assessments, prefix: prefix()) do
      add :application_id,
          references(:underwriting_applications,
            column: :id,
            name: "risk_assessments_application_id_fkey",
            type: :uuid,
            prefix: prefix()
          )
    end
  end

  def down do
    drop constraint(:risk_assessments, "risk_assessments_application_id_fkey")

    alter table(:risk_assessments, prefix: prefix()) do
      remove :application_id
    end
  end
end
