defmodule Mcp.Repo.TenantMigrations.AddAuditTrail do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:merchants_versions, primary_key: false, prefix: prefix()) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :version_action_type, :text, null: false

      add :version_source_id,
          references(:merchants,
            column: :id,
            name: "merchants_versions_version_source_id_fkey",
            type: :uuid,
            prefix: prefix()
          ),
          null: false

      add :changes, :map

      add :version_inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :version_updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end
  end

  def down do
    drop constraint(:merchants_versions, "merchants_versions_version_source_id_fkey")

    drop table(:merchants_versions, prefix: prefix())
  end
end
