defmodule Mcp.Repo.TenantMigrations.AddFeaturesToTenant do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:underwriting_reviews, primary_key: false, prefix: prefix()) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :decision, :text, null: false
      add :notes, :text
      add :risk_score, :bigint

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :application_id, :uuid
    end

    create table(:underwriting_documents, primary_key: false, prefix: prefix()) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :type, :text, null: false
      add :issuing_country, :text
      add :external_id, :text
      add :status, :text, default: "pending"

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :client_id, :uuid
    end

    create table(:underwriting_clients, primary_key: false, prefix: prefix()) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:underwriting_documents, prefix: prefix()) do
      modify :client_id,
             references(:underwriting_clients,
               column: :id,
               name: "underwriting_documents_client_id_fkey",
               type: :uuid,
               prefix: prefix()
             )
    end

    alter table(:underwriting_clients, prefix: prefix()) do
      add :type, :text, null: false
      add :email, :text
      add :phone, :text
      add :external_id, :text
      add :person_details, :map, default: %{}
      add :company_details, :map, default: %{}

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :application_id, :uuid
    end

    create table(:underwriting_checks, primary_key: false, prefix: prefix()) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :type, :text, null: false
      add :status, :text, default: "pending"
      add :outcome, :text, default: "none"
      add :external_id, :text
      add :raw_result, :map

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :client_id,
          references(:underwriting_clients,
            column: :id,
            name: "underwriting_checks_client_id_fkey",
            type: :uuid,
            prefix: prefix()
          )

      add :document_id,
          references(:underwriting_documents,
            column: :id,
            name: "underwriting_checks_document_id_fkey",
            type: :uuid,
            prefix: prefix()
          )
    end

    create table(:underwriting_applications, primary_key: false, prefix: prefix()) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:underwriting_reviews, prefix: prefix()) do
      modify :application_id,
             references(:underwriting_applications,
               column: :id,
               name: "underwriting_reviews_application_id_fkey",
               type: :uuid,
               prefix: prefix()
             )
    end

    alter table(:underwriting_clients, prefix: prefix()) do
      modify :application_id,
             references(:underwriting_applications,
               column: :id,
               name: "underwriting_clients_application_id_fkey",
               type: :uuid,
               prefix: prefix()
             )
    end

    alter table(:underwriting_applications, prefix: prefix()) do
      add :status, :text, default: "draft"
      add :application_data, :map, default: %{}
      add :risk_score, :bigint, default: 0

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :merchant_id,
          references(:merchants,
            column: :id,
            name: "underwriting_applications_merchant_id_fkey",
            type: :uuid,
            prefix: prefix()
          )
    end

    create table(:underwriting_addresses, primary_key: false, prefix: prefix()) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :line1, :text
      add :line2, :text
      add :city, :text
      add :state, :text
      add :postal_code, :text
      add :country, :text
      add :type, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :client_id,
          references(:underwriting_clients,
            column: :id,
            name: "underwriting_addresses_client_id_fkey",
            type: :uuid,
            prefix: prefix()
          )
    end

    create table(:risk_assessments, primary_key: false, prefix: prefix()) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :score, :bigint, null: false
      add :factors, :map, default: %{}
      add :recommendation, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :merchant_id,
          references(:merchants,
            column: :id,
            name: "risk_assessments_merchant_id_fkey",
            type: :uuid,
            prefix: prefix()
          )
    end
  end

  def down do
    drop constraint(:risk_assessments, "risk_assessments_merchant_id_fkey")

    drop table(:risk_assessments, prefix: prefix())

    drop constraint(:underwriting_addresses, "underwriting_addresses_client_id_fkey")

    drop table(:underwriting_addresses, prefix: prefix())

    drop constraint(:underwriting_applications, "underwriting_applications_merchant_id_fkey")

    alter table(:underwriting_applications, prefix: prefix()) do
      remove :merchant_id
      remove :updated_at
      remove :inserted_at
      remove :risk_score
      remove :application_data
      remove :status
    end

    drop constraint(:underwriting_clients, "underwriting_clients_application_id_fkey")

    alter table(:underwriting_clients, prefix: prefix()) do
      modify :application_id, :uuid
    end

    drop constraint(:underwriting_reviews, "underwriting_reviews_application_id_fkey")

    alter table(:underwriting_reviews, prefix: prefix()) do
      modify :application_id, :uuid
    end

    drop table(:underwriting_applications, prefix: prefix())

    drop constraint(:underwriting_checks, "underwriting_checks_client_id_fkey")

    drop constraint(:underwriting_checks, "underwriting_checks_document_id_fkey")

    drop table(:underwriting_checks, prefix: prefix())

    alter table(:underwriting_clients, prefix: prefix()) do
      remove :application_id
      remove :updated_at
      remove :inserted_at
      remove :company_details
      remove :person_details
      remove :external_id
      remove :phone
      remove :email
      remove :type
    end

    drop constraint(:underwriting_documents, "underwriting_documents_client_id_fkey")

    alter table(:underwriting_documents, prefix: prefix()) do
      modify :client_id, :uuid
    end

    drop table(:underwriting_clients, prefix: prefix())

    drop table(:underwriting_documents, prefix: prefix())

    drop table(:underwriting_reviews, prefix: prefix())
  end
end
