defmodule Mcp.Repo.TenantMigrations.CreateActivityAndUpdateApplication do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:underwriting_applications, prefix: prefix()) do
      add :submitted_at, :utc_datetime_usec
      add :sla_due_at, :utc_datetime_usec
    end

    create table(:underwriting_activities, primary_key: false, prefix: prefix()) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :type, :text, null: false
      add :metadata, :map, default: %{}
      add :actor_id, :uuid

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :application_id,
          references(:underwriting_applications,
            column: :id,
            name: "underwriting_activities_application_id_fkey",
            type: :uuid,
            prefix: prefix()
          )
    end
  end

  def down do
    drop constraint(:underwriting_activities, "underwriting_activities_application_id_fkey")

    drop table(:underwriting_activities, prefix: prefix())

    alter table(:underwriting_applications, prefix: prefix()) do
      remove :sla_due_at
      remove :submitted_at
    end
  end
end
