defmodule Mcp.Repo.TenantMigrations.RefactorRiskAssessment do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    rename table(:underwriting_applications), :merchant_id, to: :subject_id

    drop constraint(:underwriting_applications, "underwriting_applications_merchant_id_fkey")

    alter table(:underwriting_applications, prefix: prefix()) do
      modify :subject_id, :uuid, null: false
      add :subject_type, :text, null: false
    end

    rename table(:risk_assessments), :merchant_id, to: :subject_id

    drop constraint(:risk_assessments, "risk_assessments_merchant_id_fkey")

    alter table(:risk_assessments, prefix: prefix()) do
      modify :subject_id, :uuid, null: false
      add :subject_type, :text, null: false
    end
  end

  def down do
    alter table(:risk_assessments, prefix: prefix()) do
      remove :subject_type

      modify :subject_id,
             references(:merchants,
               column: :id,
               name: "risk_assessments_merchant_id_fkey",
               type: :uuid,
               prefix: prefix()
             ),
             null: true
    end

    rename table(:risk_assessments), :subject_id, to: :merchant_id

    alter table(:underwriting_applications, prefix: prefix()) do
      remove :subject_type

      modify :subject_id,
             references(:merchants,
               column: :id,
               name: "underwriting_applications_merchant_id_fkey",
               type: :uuid,
               prefix: prefix()
             ),
             null: true
    end

    rename table(:underwriting_applications), :subject_id, to: :merchant_id
  end
end
