defmodule Mcp.Repo.TenantMigrations.AddProcessorRegions do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:underwriting_boardings, prefix: prefix()) do
      add :rationale, :text
      add :error_metadata, :map, default: %{}
    end
  end

  def down do
    alter table(:underwriting_boardings, prefix: prefix()) do
      remove :error_metadata
      remove :rationale
    end
  end
end
