defmodule Mcp.Repo.TenantMigrations.AddProcessorAndBankProfile do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:underwriting_playbooks, primary_key: false, prefix: prefix()) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :name, :text, null: false
      add :industry, :text
      add :rules_markdown, :text, null: false
      add :thresholds, :map
      add :hash, :text
      add :is_active, :boolean, default: true

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    execute """
    DO $$
    BEGIN
      IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_schema = '#{prefix()}' AND table_name = 'document_analyses') THEN
        ALTER TABLE "#{prefix()}"."document_analyses" ADD COLUMN IF NOT EXISTS "analysis_type" text DEFAULT 'ocr';
        ALTER TABLE "#{prefix()}"."document_analyses" ADD COLUMN IF NOT EXISTS "forensics_report" jsonb;
        ALTER TABLE "#{prefix()}"."document_analyses" ADD COLUMN IF NOT EXISTS "camera_telemetry" jsonb;
      END IF;
    END
    $$;
    """
  end

  def down do
    alter table(:document_analyses, prefix: prefix()) do
      remove :camera_telemetry
      remove :forensics_report
      remove :analysis_type
    end

    drop table(:underwriting_playbooks, prefix: prefix())
  end
end
