defmodule Mcp.Repo.TenantMigrations.AddHealedDataToApplications do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:underwriting_applications, prefix: prefix()) do
      add :healed_data, :map, default: %{}
    end
  end

  def down do
    alter table(:underwriting_applications, prefix: prefix()) do
      remove :healed_data
    end
  end
end
