defmodule Mcp.Repo.TenantMigrations.CreateUnderwritingNotes do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:underwriting_notes, primary_key: false, prefix: prefix()) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :content, :text, null: false
      add :visibility, :text, default: "internal"
      add :mentions, {:array, :uuid}, default: []

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :application_id,
          references(:underwriting_applications,
            column: :id,
            name: "underwriting_notes_application_id_fkey",
            type: :uuid,
            prefix: prefix()
          )

      add :author_id,
          references(:users,
            column: :id,
            name: "underwriting_notes_author_id_fkey",
            type: :uuid,
            prefix: "platform"
          )
    end
  end

  def down do
    drop constraint(:underwriting_notes, "underwriting_notes_application_id_fkey")

    drop constraint(:underwriting_notes, "underwriting_notes_author_id_fkey")

    drop table(:underwriting_notes, prefix: prefix())
  end
end
