defmodule Mcp.Repo.TenantMigrations.AddBoardingResource do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:underwriting_boardings, primary_key: false, prefix: prefix()) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :mid, :text
      add :tid, :text
      add :status, :text, default: "pending"
      add :metadata, :map, default: %{}

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :application_id,
          references(:underwriting_applications,
            column: :id,
            name: "underwriting_boardings_application_id_fkey",
            type: :uuid,
            prefix: prefix()
          ),
          null: false

      add :processor_id,
          references(:underwriting_processors,
            column: :id,
            name: "underwriting_boardings_processor_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :bank_profile_id,
          references(:underwriting_bank_profiles,
            column: :id,
            name: "underwriting_boardings_bank_profile_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end
  end

  def down do
    drop constraint(:underwriting_boardings, "underwriting_boardings_application_id_fkey")

    drop constraint(:underwriting_boardings, "underwriting_boardings_processor_id_fkey")

    drop constraint(:underwriting_boardings, "underwriting_boardings_bank_profile_id_fkey")

    drop table(:underwriting_boardings, prefix: prefix())
  end
end
