import Config

# Configure CLDR backend for Money library
config :ex_cldr,
  default_backend: Mcp.Cldr

config :ex_money,
  default_cldr_backend: Mcp.Cldr

# JWT signing secret for development
config :mcp, :token_signing_secret, "dev-secret-change-in-production-use-env-var"

# Configure Oban for development - use testing mode to prevent job processing
config :mcp, Oban,
  repo: Mcp.Repo,
  testing: :manual,  # This prevents automatic job processing
  queues: false,       # Don't start queues in development
  plugins: false      # Don't start plugins in development

# Configure your database with environment variables
config :mcp, Mcp.Repo,
  username: System.get_env("POSTGRES_USER", "base_mcp_dev"),
  password: System.get_env("POSTGRES_PASSWORD", "mcp_password"),
  hostname: "localhost",
  database: System.get_env("POSTGRES_DB", "base_mcp_dev"),
  port: String.to_integer(System.get_env("POSTGRES_PORT", "41789")),
  show_sensitive_data_on_connection_error: true,
  pool_size: 10,
  ssl: false

# Override JWT settings for development
config :mcp, McpWeb.Endpoint,
  # Development-specific session options (less secure for convenience)
  session_options: [
    store: :cookie,
    key: "_mcp_key",
    signing_salt: "ATUG2KBX",
    encryption_salt: "SOME_ENCRYPTION_SALT",
    same_site: "Lax",
    # Allow HTTP in development
    secure: false,
    http_only: true,
    # 30 days
    max_age: 30 * 24 * 60 * 60
  ]

# Configure Redis for caching
config :mcp, Mcp.Redis,
  host: "localhost",
  port: String.to_integer(System.get_env("REDIS_PORT", "48234")),
  database: 0,
  reconnect_interval: :timer.seconds(5)

# Configure MinIO (S3-compatible) storage
config :ex_aws,
  access_key_id: System.get_env("MINIO_ROOT_USER", "minioadmin"),
  secret_access_key: System.get_env("MINIO_ROOT_PASSWORD", "minioadmin123"),
  region: "us-east-1"

config :ex_aws, :s3,
  scheme: "http://",
  host: "localhost",
  port: String.to_integer(System.get_env("MINIO_PORT", "49723"))

# Configure Vault for secrets management
config :vaultex,
  vault_address: "http://localhost:#{System.get_env("VAULT_PORT", "44567")}",
  vault_token: System.get_env("VAULT_DEV_ROOT_TOKEN_ID", "dev-root-token"),
  auth_method: :token

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
config :mcp, McpWeb.Endpoint,
  # Binding to loopback ipv4 address prevents access from other machines.
  # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
  http: [ip: {127, 0, 0, 1}, port: String.to_integer(System.get_env("PORT") || "4000")],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "cZfHUOFs72vIEaoV68jK7VqYBMT0y7sIFS9h8HpIdeykEVAEt33d6HVQgEqWe4iU",
  watchers: [
    esbuild: {Esbuild, :install_and_run, [:mcp, ~w(--sourcemap=inline --watch)]},
    tailwind: {Tailwind, :install_and_run, [:mcp, ~w(--watch)]}
  ]

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Watch static and templates for browser reloading.
config :mcp, McpWeb.Endpoint,
  live_reload: [
    web_console_logger: true,
    patterns: [
      ~r"priv/static/(?!uploads/).*(js|css|png|jpeg|jpg|gif|svg)$",
      ~r"priv/gettext/.*(po)$",
      ~r"lib/mcp_web/(?:controllers|live|components|router)/?.*\.(ex|heex)$"
    ]
  ]

# Enable dev routes for dashboard and mailbox
config :mcp, dev_routes: true

# Do not include metadata nor timestamps in development logs
config :logger, :default_formatter, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

config :phoenix_live_view,
  # Include debug annotations and locations in rendered markup.
  # Changing this configuration will require mix clean and a full recompile.
  debug_heex_annotations: true,
  debug_attributes: true,
  # Enable helpful, but potentially expensive runtime checks
  enable_expensive_runtime_checks: true

# Disable swoosh api client as it is only required for production adapters.
config :swoosh, :api_client, false
