defmodule Mcp.Repo.Migrations.AddReviewRequiredToPipeline do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:pipelines) do
      add :review_required, :boolean, null: false, default: false
    end
  end

  def down do
    alter table(:pipelines) do
      remove :review_required
    end
  end
end
