defmodule Mcp.Repo.Migrations.RefactorApiKeyScopes do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:api_keys) do
      remove :allowed_reseller_ids
      remove :allowed_merchant_ids
      add :permissions, {:array, :text}, null: false, default: []
    end
  end

  def down do
    alter table(:api_keys) do
      remove :permissions
      add :allowed_merchant_ids, {:array, :uuid}, null: false, default: []
      add :allowed_reseller_ids, {:array, :uuid}, null: false, default: []
    end
  end
end
