defmodule Mcp.Repo.Migrations.CreateInvitations do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    execute("ALTER TABLE platform.teams ADD COLUMN IF NOT EXISTS slug text NOT NULL DEFAULT ''")
    execute("ALTER TABLE platform.teams ALTER COLUMN slug DROP DEFAULT")

    execute(
      "ALTER TABLE platform.teams ADD COLUMN IF NOT EXISTS entity_type text NOT NULL DEFAULT ''"
    )

    execute("ALTER TABLE platform.teams ALTER COLUMN entity_type DROP DEFAULT")

    execute(
      "ALTER TABLE platform.teams ADD COLUMN IF NOT EXISTS entity_id uuid NOT NULL DEFAULT '00000000-0000-0000-0000-000000000000'"
    )

    execute("ALTER TABLE platform.teams ALTER COLUMN entity_id DROP DEFAULT")

    execute("ALTER TABLE platform.team_members ADD COLUMN IF NOT EXISTS user_profile_id uuid")

    execute("CREATE SCHEMA IF NOT EXISTS platform")

    create table(:invitations, primary_key: false, prefix: "platform") do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :email, :text, null: false
      add :token, :text, null: false
      add :status, :text, null: false, default: "pending"
      add :role, :text, null: false, default: "member"
      add :permissions, {:array, :text}, default: []
      add :entity_type, :text
      add :entity_id, :uuid
      add :expires_at, :utc_datetime, null: false
      add :accepted_at, :utc_datetime

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :inviter_id,
          references(:users,
            column: :id,
            name: "invitations_inviter_id_fkey",
            type: :uuid,
            prefix: "platform"
          )

      add :team_id,
          references(:teams,
            column: :id,
            name: "invitations_team_id_fkey",
            type: :uuid,
            prefix: "platform"
          )

      add :scope_id,
          references(:team_scopes,
            column: :id,
            name: "invitations_scope_id_fkey",
            type: :uuid,
            prefix: "platform"
          )
    end

    create unique_index(:invitations, [:token],
             name: "invitations_token_index",
             prefix: "platform"
           )
  end

  def down do
    drop_if_exists unique_index(:invitations, [:token],
                     name: "invitations_token_index",
                     prefix: "platform"
                   )

    drop constraint(:invitations, "invitations_inviter_id_fkey", prefix: "platform")

    drop constraint(:invitations, "invitations_team_id_fkey", prefix: "platform")

    drop constraint(:invitations, "invitations_scope_id_fkey", prefix: "platform")

    drop table(:invitations, prefix: "platform")

    alter table(:team_members, prefix: "platform") do
      remove :user_profile_id
    end

    alter table(:teams, prefix: "platform") do
      remove :entity_id
      remove :entity_type
      remove :slug
    end
  end
end
