defmodule Mcp.Repo.Migrations.AddPayfacConfig do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:payfac_configurations, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :provider, :text, default: "mock"
      add :provider_api_key, :text
      add :auto_approve_threshold, :bigint, default: 90
      add :auto_reject_threshold, :bigint, default: 40

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :tenant_id,
          references(:tenants,
            column: :id,
            name: "payfac_configurations_tenant_id_fkey",
            type: :uuid,
            prefix: "platform"
          )
    end
  end

  def down do
    drop constraint(:payfac_configurations, "payfac_configurations_tenant_id_fkey")

    drop table(:payfac_configurations)
  end
end
