defmodule Mcp.Repo.Migrations.CreateUnderwritingAndFixFinance do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create_if_not_exists table(:underwriting_reviews, primary_key: false, prefix: "public") do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :decision, :text, null: false
      add :risk_score, :decimal
      add :reviewer_notes, :text
      add :model_version, :text

      add :reviewer_id,
          references(:users,
            column: :id,
            name: "underwriting_reviews_reviewer_id_fkey",
            type: :uuid,
            prefix: "platform"
          )

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :application_id, :uuid, null: false
    end

    execute("CREATE SCHEMA IF NOT EXISTS platform")

    create_if_not_exists table(:phones, primary_key: false, prefix: "platform") do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :owner_type, :text, null: false
      add :owner_id, :uuid, null: false
      add :phone_type, :text
      add :label, :text
      add :phone, :text, null: false
      add :country_code, :text, default: "US"
      add :extension, :text
      add :is_verified, :boolean, default: false
      add :verified_at, :utc_datetime
      add :verification_code, :text
      add :verification_sent_at, :utc_datetime
      add :can_sms, :boolean, default: false
      add :can_voice, :boolean, default: true
      add :is_primary, :boolean, default: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    execute("CREATE SCHEMA IF NOT EXISTS platform")

    create_if_not_exists table(:emails, primary_key: false, prefix: "platform") do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :owner_type, :text, null: false
      add :owner_id, :uuid, null: false
      add :email_type, :text
      add :label, :text
      add :email, :citext, null: false
      add :is_verified, :boolean, default: false
      add :verified_at, :utc_datetime
      add :verification_token, :text
      add :verification_sent_at, :utc_datetime
      add :is_primary, :boolean, default: false
      add :can_receive_marketing, :boolean, default: false
      add :can_receive_transactional, :boolean, default: true

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    execute("CREATE SCHEMA IF NOT EXISTS platform")

    create_if_not_exists table(:addresses, primary_key: false, prefix: "platform") do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :owner_type, :text, null: false
      add :owner_id, :uuid, null: false
      add :address_type, :text
      add :label, :text
      add :line1, :text, null: false
      add :line2, :text
      add :city, :text, null: false
      add :state, :text
      add :postal_code, :text, null: false
      add :country, :text, null: false, default: "US"
      add :is_verified, :boolean, default: false
      add :verified_at, :utc_datetime
      add :verification_method, :text
      add :is_primary, :boolean, default: false
      add :notes, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create_if_not_exists table(:underwriting_applications, primary_key: false, prefix: "public") do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:underwriting_reviews, prefix: "public") do
      modify :application_id,
             references(:underwriting_applications,
               column: :id,
               name: "underwriting_reviews_application_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:underwriting_applications, prefix: "public") do
      add :status, :text, null: false, default: "draft"
      add :application_data, :map, default: %{}
      add :risk_score, :bigint
      add :merchant_id, :uuid

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    drop_if_exists index(:users, [:email], prefix: "platform")

    alter table(:users, prefix: "platform") do
      # remove :oauth_tokens
      # remove :backup_codes
      # remove :totp_secret
      modify :last_sign_in_ip, :inet
      # add :role, :text, null: false, default: "user"
      # add :tenant_id, :uuid
      # add :encrypted_totp_secret, :binary
      # add :encrypted_backup_codes, :binary
      # add :encrypted_oauth_tokens, :binary
    end

    # rename table(:tenants, prefix: "platform"), :company_name, to: :name

    alter table(:tenant_settings) do
      modify :tenant_id, :uuid
    end

    alter table(:tenant_branding) do
      modify :tenant_id, :uuid
    end

    create_if_not_exists table(:underwriting_risk_assessments, primary_key: false, prefix: "public") do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :risk_score, :decimal
      add :risk_level, :text
      add :risk_factors, :map, default: %{}
      add :recommended_actions, :map, default: %{}
      add :merchant_id, :uuid

      add :application_id,
          references(:underwriting_applications,
            column: :id,
            name: "underwriting_risk_assessments_application_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create_if_not_exists table(:documents, primary_key: false, prefix: "public") do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :content, :text, null: false
      add :metadata, :map, null: false, default: %{}
      add :embedding, :vector

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    drop_if_exists index(:documents, ["embedding vector_cosine_ops"],
                     name: "documents_embedding_index"
                   )

    create index(:documents, ["embedding vector_cosine_ops"],
             name: "documents_embedding_index",
             using: "hnsw"
           )
  end

  def down do
    drop_if_exists index(:documents, ["embedding vector_cosine_ops"],
                     name: "documents_embedding_index"
                   )

    drop table(:documents)

    drop constraint(
           :underwriting_risk_assessments,
           "underwriting_risk_assessments_merchant_id_fkey"
         )

    drop constraint(
           :underwriting_risk_assessments,
           "underwriting_risk_assessments_application_id_fkey"
         )

    drop table(:underwriting_risk_assessments)

    alter table(:tenant_branding) do
      modify :tenant_id, :text
    end

    alter table(:tenant_settings) do
      modify :tenant_id, :text
    end

    rename table(:tenants, prefix: "platform"), :name, to: :company_name

    alter table(:users, prefix: "platform") do
      remove :encrypted_oauth_tokens
      remove :encrypted_backup_codes
      remove :encrypted_totp_secret
      remove :tenant_id
      remove :role
      modify :last_sign_in_ip, :text
      add :totp_secret, :text
      add :backup_codes, {:array, :text}, default: []
      add :oauth_tokens, :map, default: %{}
    end

    create index(:users, [:email], unique: true, prefix: "platform")

    drop constraint(:underwriting_applications, "underwriting_applications_merchant_id_fkey")

    alter table(:underwriting_applications) do
      remove :updated_at
      remove :inserted_at
      remove :merchant_id
      remove :risk_score
      remove :application_data
      remove :status
    end

    drop constraint(:underwriting_reviews, "underwriting_reviews_application_id_fkey")

    alter table(:underwriting_reviews) do
      modify :application_id, :uuid
    end

    drop table(:underwriting_applications)

    drop table(:addresses, prefix: "platform")

    drop table(:emails, prefix: "platform")

    drop table(:phones, prefix: "platform")

    drop constraint(:underwriting_reviews, "underwriting_reviews_reviewer_id_fkey")

    drop table(:underwriting_reviews)
  end
end
