defmodule Mcp.Repo.Migrations.AddClientToDocuments do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:underwriting_documents) do
      add :client_id, :uuid
    end
  end

  def down do
    drop constraint(:underwriting_documents, "underwriting_documents_client_id_fkey")

    alter table(:underwriting_documents) do
      remove :client_id
    end
  end
end
