defmodule Mcp.Repo.Migrations.GenerateApiKeys do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:api_keys) do
      modify :permissions, {:array, :text}, null: true
      modify :name, :text, null: true
      add :type, :text, default: "developer"
      add :expires_at, :utc_datetime_usec
      add :revoked_at, :utc_datetime_usec
      add :owner_id, :uuid
      add :owner_type, :text
    end
  end

  def down do
    alter table(:api_keys) do
      remove :owner_type
      remove :owner_id
      remove :revoked_at
      remove :expires_at
      remove :type
      modify :name, :text, null: false
      modify :permissions, {:array, :text}, null: false
    end
  end
end
