defmodule Mcp.Repo.Migrations.AddApiKeyIdToLlmUsage do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:llm_usages) do
      remove :execution_id
      modify :cost, :decimal, null: false, default: "0.0"
      modify :total_tokens, :bigint, default: nil
      modify :completion_tokens, :bigint, default: nil
      modify :prompt_tokens, :bigint, default: nil
      add :api_key_id, :uuid

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end
  end

  def down do
    alter table(:llm_usages) do
      remove :updated_at
      remove :api_key_id
      modify :prompt_tokens, :bigint, default: 0
      modify :completion_tokens, :bigint, default: 0
      modify :total_tokens, :bigint, default: 0
      modify :cost, :decimal, null: true, default: nil

      add :execution_id,
          references(:executions,
            column: :id,
            name: "llm_usages_execution_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end
  end
end
