defmodule Mcp.Repo.Migrations.FixGdprSchemasAndAddEstimatedCompletion do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    execute("CREATE SCHEMA IF NOT EXISTS platform")
    execute("DROP TABLE IF EXISTS platform.gdpr_exports CASCADE")
    execute("DROP TABLE IF EXISTS platform.gdpr_audit_trail CASCADE")

    create table(:gdpr_exports, primary_key: false, prefix: "platform") do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :status, :text, default: "pending"
      add :format, :text, null: false
      add :purpose, :text, default: "user_request"
      add :file_path, :text
      add :file_size, :bigint
      add :download_url, :text
      add :downloaded_at, :utc_datetime_usec
      add :completed_at, :utc_datetime_usec
      add :error_message, :text
      add :expires_at, :utc_datetime_usec
      add :estimated_completion, :utc_datetime_usec

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :user_id,
          references(:users,
            column: :id,
            name: "gdpr_exports_user_id_fkey",
            type: :uuid,
            prefix: "platform"
          ),
          null: false

      add :actor_id, :uuid
    end

    # alter table(:users, prefix: "platform") do
    #   modify :role, :text, null: true
    #   modify :status, :text, null: true
    #   modify :hashed_password, :text, null: true
    #   add :gdpr_deletion_requested_at, :utc_datetime_usec
    #   add :gdpr_deletion_reason, :text
    #   add :gdpr_anonymized_at, :utc_datetime_usec
    #   add :gdpr_data_export_token, :uuid
    #   add :gdpr_last_exported_at, :utc_datetime_usec
    #   add :gdpr_consent_record, :map, default: %{}
    #   add :gdpr_marketing_consent, :boolean, default: false
    #   add :gdpr_analytics_consent, :boolean, default: false
    #   add :gdpr_deletion_request_ip, :text
    #   add :gdpr_deletion_request_user_agent, :text
    # end

    execute("CREATE SCHEMA IF NOT EXISTS platform")

    create table(:gdpr_audit_trail, primary_key: false, prefix: "platform") do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true

      add :user_id,
          references(:users,
            column: :id,
            name: "gdpr_audit_trail_user_id_fkey",
            type: :uuid,
            prefix: "platform"
          ),
          null: false

      add :action_type, :text, null: false
      add :actor_type, :text
      add :actor_id, :uuid
      add :ip_address, :text
      add :user_agent, :text
      add :request_id, :text
      add :data_categories, {:array, :text}, default: []
      add :legal_basis, :text
      add :retention_period_days, :bigint
      add :details, :map, default: %{}
      add :processed_at, :utc_datetime_usec

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end
  end

  def down do
    drop constraint(:gdpr_audit_trail, "gdpr_audit_trail_user_id_fkey", prefix: "platform")

    drop table(:gdpr_audit_trail, prefix: "platform")

    alter table(:users, prefix: "platform") do
      remove :gdpr_deletion_request_user_agent
      remove :gdpr_deletion_request_ip
      remove :gdpr_analytics_consent
      remove :gdpr_marketing_consent
      remove :gdpr_consent_record
      remove :gdpr_last_exported_at
      remove :gdpr_data_export_token
      remove :gdpr_anonymized_at
      remove :gdpr_deletion_reason
      remove :gdpr_deletion_requested_at
      modify :hashed_password, :text, null: false
      modify :status, :text, null: false
      modify :role, :text, null: false
    end

    drop constraint(:gdpr_exports, "gdpr_exports_user_id_fkey", prefix: "platform")

    drop table(:gdpr_exports, prefix: "platform")
  end
end
