defmodule Mcp.Repo.Migrations.AddPlatformMigrationTables do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    execute("DROP TABLE IF EXISTS platform.data_migration_logs CASCADE")
    execute("DROP TABLE IF EXISTS platform.data_migration_records CASCADE")
    execute("DROP TABLE IF EXISTS platform.data_migrations CASCADE")

    execute("CREATE SCHEMA IF NOT EXISTS platform")

    create table(:data_migrations, primary_key: false, prefix: "platform") do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :migration_type, :text, null: false
      add :name, :text, null: false
      add :description, :text
      add :status, :text, default: "pending"
      add :source_format, :text
      add :target_format, :text
      add :source_config, :map, default: %{}
      add :target_config, :map, default: %{}
      add :field_mappings, :map, default: %{}
      add :validation_rules, :map, default: %{}
      add :batch_size, :bigint, default: 100
      add :total_records, :bigint, default: 0
      add :processed_records, :bigint, default: 0
      add :failed_records, :bigint, default: 0
      add :progress_percentage, :float, default: 0.0
      add :file_path, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :tenant_id,
          references(:tenants,
            column: :id,
            name: "data_migrations_tenant_id_fkey",
            type: :uuid,
            prefix: "platform"
          ),
          null: false
    end

    execute("CREATE SCHEMA IF NOT EXISTS platform")

    create table(:data_migration_records, primary_key: false, prefix: "platform") do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :source_data, :map
      add :target_data, :map
      add :status, :text, default: "pending"
      add :error_message, :text
      add :validation_errors, :map

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :migration_id,
          references(:data_migrations,
            column: :id,
            name: "data_migration_records_migration_id_fkey",
            type: :uuid,
            prefix: "platform"
          ),
          null: false
    end



    execute("CREATE SCHEMA IF NOT EXISTS platform")

    create table(:data_migration_logs, primary_key: false, prefix: "platform") do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :message, :text, null: false
      add :level, :text, default: "info"
      add :details, :map

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :migration_id,
          references(:data_migrations,
            column: :id,
            name: "data_migration_logs_migration_id_fkey",
            type: :uuid,
            prefix: "platform"
          ),
          null: false
    end
  end

  def down do
    drop constraint(:data_migration_logs, "data_migration_logs_migration_id_fkey",
           prefix: "platform"
         )

    drop table(:data_migration_logs, prefix: "platform")

    alter table(:auth_tokens, prefix: "platform") do
      remove :jti
      remove :device_id
      remove :session_id
    end

    drop constraint(:data_migration_records, "data_migration_records_migration_id_fkey",
           prefix: "platform"
         )

    drop table(:data_migration_records, prefix: "platform")

    drop constraint(:data_migrations, "data_migrations_tenant_id_fkey", prefix: "platform")

    drop table(:data_migrations, prefix: "platform")

    alter table(:accounts, prefix: "finance") do
      remove :type
    end
  end
end
