defmodule Mcp.Repo.Migrations.CreateCustomDomains do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:custom_domains, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :domain, :text, null: false
      add :state, :text, null: false, default: "pending_verification"
      add :verification_record_name, :text, null: false, default: "_mcp_challenge"
      add :verification_record_value, :text, null: false

      add :tenant_id,
          references(:tenants,
            column: :id,
            name: "custom_domains_tenant_id_fkey",
            type: :uuid,
            prefix: "platform"
          ),
          null: false
    end

    alter table(:transfers, prefix: "finance") do
      modify :amount, :money_with_currency
    end
  end

  def down do
    alter table(:transfers, prefix: "finance") do
      modify :amount, :map
    end

    drop constraint(:custom_domains, "custom_domains_tenant_id_fkey")

    drop table(:custom_domains)
  end
end
