defmodule Mcp.Repo.Migrations.AddChat do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    IO.puts("Running AddChat migration...")
    execute "DROP TABLE IF EXISTS messages CASCADE"
    execute "DROP TABLE IF EXISTS conversations CASCADE"

    create table(:conversations, primary_key: false, prefix: "public") do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :title, :text
      add :inserted_at, :utc_datetime_usec, null: false, default: fragment("(now() AT TIME ZONE 'utc')")
      add :updated_at, :utc_datetime_usec, null: false, default: fragment("(now() AT TIME ZONE 'utc')")
      add :user_id, :uuid, null: false
    end

    create table(:messages, primary_key: false, prefix: "public") do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :text, :text, null: false
      add :tool_calls, {:array, :map}
      add :tool_results, {:array, :map}
      add :source, :text, null: false, default: "user"
      add :complete, :boolean, null: false, default: true
      add :conversation_id, references(:conversations, type: :uuid, on_delete: :nothing, prefix: "public"), null: false
      add :response_to_id, references(:messages, type: :uuid, on_delete: :nothing, prefix: "public")
      add :inserted_at, :utc_datetime_usec, null: false, default: fragment("(now() AT TIME ZONE 'utc')")
      add :updated_at, :utc_datetime_usec, null: false, default: fragment("(now() AT TIME ZONE 'utc')")
    end

    execute "DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'conversations_user_id_fkey') THEN ALTER TABLE public.conversations ADD CONSTRAINT conversations_user_id_fkey FOREIGN KEY (user_id) REFERENCES platform.users(id); END IF; END $$;",
            "ALTER TABLE public.conversations DROP CONSTRAINT IF EXISTS conversations_user_id_fkey"
  end

  def down do
    drop constraint(:conversations, "conversations_user_id_fkey")

    alter table(:conversations) do
      remove :user_id
      remove :updated_at
      remove :inserted_at
      remove :title
    end

    drop constraint(:messages, "messages_conversation_id_fkey")

    drop constraint(:messages, "messages_response_to_id_fkey")

    alter table(:messages) do
      modify :response_to_id, :uuid
      modify :conversation_id, :uuid
    end

    drop table(:conversations)

    drop table(:messages)
  end
end
