defmodule Mcp.Repo.Migrations.AddApiKeyConfig do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:api_keys) do
      add :rate_limit, :bigint
      add :spending_limit, :decimal
      add :scopes, {:array, :text}, null: false, default: []
    end
  end

  def down do
    alter table(:api_keys) do
      remove :scopes
      remove :spending_limit
      remove :rate_limit
    end
  end
end
