defmodule Mcp.Repo.Migrations.AddRoutingConfigToBlueprint do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:agent_blueprints) do
      add :routing_config, :map, null: false, default: %{mode: "single", primary_provider: "ollama", fallback_provider: "openrouter", min_confidence: 0.8}
    end
  end

  def down do
    alter table(:agent_blueprints) do
      remove :routing_config
    end
  end
end
