defmodule Mcp.Repo.Migrations.AddUsageTrackingEntitiesFixed do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:llm_usages) do
      add :reseller_id, :uuid
      add :merchant_id, :uuid
    end

    alter table(:agent_blueprints) do
      modify :routing_config, :map, null: true
      add :knowledge_base_ids, {:array, :uuid}, default: []
    end
  end

  def down do
    alter table(:agent_blueprints) do
      remove :knowledge_base_ids
      modify :routing_config, :map, null: false
    end

    drop constraint(:llm_usages, "llm_usages_merchant_id_fkey")

    alter table(:llm_usages) do
      remove :merchant_id
      remove :reseller_id
    end
  end
end
