defmodule Mcp.Repo.Migrations.AddDescriptionToTransfer do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:transfers, prefix: "finance") do
      add :description, :text
    end
  end

  def down do
    alter table(:transfers, prefix: "finance") do
      remove :description
    end
  end
end
