defmodule Mcp.Repo.Migrations.FixTransferAmount do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    execute "TRUNCATE finance.transfers CASCADE"
    execute "ALTER TABLE finance.transfers ALTER COLUMN id DROP DEFAULT"

    # Create Type
    execute """
    DO $$
    BEGIN
      IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'money_with_currency' AND typnamespace = 'public'::regnamespace) THEN
        CREATE TYPE public.money_with_currency AS (currency varchar, amount numeric);
      END IF;
    END
    $$;
    """

    execute "ALTER TABLE finance.transfers DROP COLUMN amount"
    execute "ALTER TABLE finance.transfers ADD COLUMN amount public.money_with_currency"

    execute "ALTER TABLE finance.transfers ALTER COLUMN id TYPE bytea USING id::text::bytea",
            "ALTER TABLE finance.transfers ALTER COLUMN id TYPE uuid USING encode(id, 'escape')::uuid"
  end

  def down do
    alter table(:transfers, prefix: "finance") do
      modify :id, :uuid, default: fragment("gen_random_uuid()")
    end
  end
end
