defmodule Mcp.Repo.Migrations.AddKnowledgeBaseFixedV2 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    execute "DROP EXTENSION IF EXISTS vector CASCADE"
    execute "CREATE EXTENSION vector"

    create table(:knowledge_bases, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :name, :text, null: false
      add :description, :text
      add :reseller_id, :uuid

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :tenant_id,
          references(:tenants,
            column: :id,
            name: "knowledge_bases_tenant_id_fkey",
            type: :uuid,
            prefix: "platform"
          )

      add :merchant_id, :uuid
    end

    create table(:documents, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :content, :text, null: false
      add :metadata, :map, null: false, default: %{}
      add :embedding, :vector, size: 1536
      add :reseller_id, :uuid

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :knowledge_base_id,
          references(:knowledge_bases,
            column: :id,
            name: "documents_knowledge_base_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :tenant_id,
          references(:tenants,
            column: :id,
            name: "documents_tenant_id_fkey",
            type: :uuid,
            prefix: "platform"
          )

      add :merchant_id, :uuid
    end

    create index(:documents, ["embedding vector_cosine_ops"],
             name: "documents_embedding_index",
             using: "hnsw"
           )
  end

  def down do
    drop constraint(:documents, "documents_knowledge_base_id_fkey")

    drop constraint(:documents, "documents_tenant_id_fkey")

    drop constraint(:documents, "documents_merchant_id_fkey")

    drop_if_exists index(:documents, ["embedding vector_cosine_ops"],
                     name: "documents_embedding_index"
                   )

    drop table(:documents)

    drop constraint(:knowledge_bases, "knowledge_bases_tenant_id_fkey")

    drop constraint(:knowledge_bases, "knowledge_bases_merchant_id_fkey")

    drop table(:knowledge_bases)
  end
end
