defmodule Mcp.Repo.Migrations.FixBalanceTransferId do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    execute "TRUNCATE finance.balances CASCADE"

    execute "ALTER TABLE finance.balances ALTER COLUMN transfer_id TYPE bytea USING transfer_id::text::bytea",
            "ALTER TABLE finance.balances ALTER COLUMN transfer_id TYPE uuid USING encode(transfer_id, 'escape')::uuid"

    execute "ALTER TABLE finance.balances DROP COLUMN balance"
    execute "ALTER TABLE finance.balances ADD COLUMN balance public.money_with_currency"

    alter table(:transfers, prefix: "finance") do
      modify :amount, :money_with_currency
    end
  end

  def down do
    alter table(:transfers, prefix: "finance") do
      modify :amount, :money_with_currency
    end

    alter table(:balances, prefix: "finance") do
      modify :transfer_id, :uuid
    end
  end
end
