defmodule Mcp.Repo.Migrations.AddWebhooksV2 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:webhook_deliveries, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :event, :text, null: false
      add :payload, :map, null: false
      add :status, :text, null: false, default: "pending"
      add :response_code, :bigint
      add :response_body, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :endpoint_id, :uuid, null: false
    end

    create table(:webhook_endpoints, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:webhook_deliveries) do
      modify :endpoint_id,
             references(:webhook_endpoints,
               column: :id,
               name: "webhook_deliveries_endpoint_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:webhook_endpoints) do
      add :url, :text, null: false
      add :secret, :text, null: false
      add :events, {:array, :text}, null: false, default: []
      add :enabled, :boolean, null: false, default: true

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :tenant_id,
          references(:tenants,
            column: :id,
            name: "webhook_endpoints_tenant_id_fkey",
            type: :uuid,
            prefix: "platform"
          )

      add :merchant_id, :uuid
    end
  end

  def down do
    drop constraint(:webhook_endpoints, "webhook_endpoints_tenant_id_fkey")

    drop constraint(:webhook_endpoints, "webhook_endpoints_merchant_id_fkey")

    alter table(:webhook_endpoints) do
      remove :merchant_id
      remove :tenant_id
      remove :updated_at
      remove :inserted_at
      remove :enabled
      remove :events
      remove :secret
      remove :url
    end

    drop constraint(:webhook_deliveries, "webhook_deliveries_endpoint_id_fkey")

    alter table(:webhook_deliveries) do
      modify :endpoint_id, :uuid
    end

    drop table(:webhook_endpoints)

    drop table(:webhook_deliveries)
  end
end
