defmodule Mcp.Repo.Migrations.CreateTeams do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    execute("CREATE SCHEMA IF NOT EXISTS platform")

    create_if_not_exists table(:team_scopes, primary_key: false, prefix: "platform") do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :entity_type, :text, null: false
      add :entity_id, :uuid, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :team_id, :uuid, null: false
    end

    execute("CREATE SCHEMA IF NOT EXISTS platform")

    execute(
      "CREATE TABLE IF NOT EXISTS platform.teams (id uuid PRIMARY KEY DEFAULT gen_random_uuid())"
    )

    execute("""
    ALTER TABLE platform.teams
    ADD COLUMN IF NOT EXISTS name text,
    ADD COLUMN IF NOT EXISTS description text,
    ADD COLUMN IF NOT EXISTS permissions text[] DEFAULT '{}',
    ADD COLUMN IF NOT EXISTS inserted_at timestamp(0) without time zone DEFAULT (now() AT TIME ZONE 'utc'),
    ADD COLUMN IF NOT EXISTS updated_at timestamp(0) without time zone DEFAULT (now() AT TIME ZONE 'utc')
    """)

    # Ensure NOT NULL constraints if needed, but existing table implies they might be there.
    # We set defaults where appropriate.
    execute("ALTER TABLE platform.teams ALTER COLUMN name SET NOT NULL")
    execute("ALTER TABLE platform.teams ALTER COLUMN permissions SET NOT NULL")
    execute("ALTER TABLE platform.teams ALTER COLUMN inserted_at SET NOT NULL")
    execute("ALTER TABLE platform.teams ALTER COLUMN updated_at SET NOT NULL")

    # Add FK if not exists (Postgres doesn't support ADD CONSTRAINT IF NOT EXISTS directly,
    # so we use a DO block or just try/catch via Elixir, but using simple alter is risky if it exists.
    # However, since we are doing a reset, and team_scopes was dropped/created, we can assume constraint is gone.
    alter table(:team_scopes, prefix: "platform") do
      modify :team_id,
             references(:teams, column: :id, name: "team_scopes_team_id_fkey", type: :uuid)
    end

    execute("CREATE SCHEMA IF NOT EXISTS platform")

    execute(
      "CREATE TABLE IF NOT EXISTS platform.team_members (id uuid PRIMARY KEY DEFAULT gen_random_uuid())"
    )

    execute("""
    ALTER TABLE platform.team_members
    ADD COLUMN IF NOT EXISTS role text DEFAULT 'member',
    ADD COLUMN IF NOT EXISTS user_id uuid,
    ADD COLUMN IF NOT EXISTS user_profile_id uuid,
    ADD COLUMN IF NOT EXISTS team_id uuid,
    ADD COLUMN IF NOT EXISTS inserted_at timestamp(0) without time zone DEFAULT (now() AT TIME ZONE 'utc'),
    ADD COLUMN IF NOT EXISTS updated_at timestamp(0) without time zone DEFAULT (now() AT TIME ZONE 'utc')
    """)

    execute("ALTER TABLE platform.team_members ALTER COLUMN role SET NOT NULL")
    # user_id and team_id should be not null, but if they are new, they are null until populated?
    # But this is schema def.
    # If table exists and has data, SET NOT NULL might fail if nulls exist.
    # But for fresh migration it is fine.
    execute("ALTER TABLE platform.team_members ALTER COLUMN user_id SET NOT NULL")
    execute("ALTER TABLE platform.team_members ALTER COLUMN team_id SET NOT NULL")
    execute("ALTER TABLE platform.team_members ALTER COLUMN inserted_at SET NOT NULL")
    execute("ALTER TABLE platform.team_members ALTER COLUMN updated_at SET NOT NULL")

    # Add FK constraints
    execute(
      "ALTER TABLE platform.team_members DROP CONSTRAINT IF EXISTS team_members_team_id_fkey"
    )

    execute(
      "ALTER TABLE platform.team_members DROP CONSTRAINT IF EXISTS team_members_user_id_fkey"
    )

    # Drop phantom constraint from ghost migration
    execute(
      "ALTER TABLE platform.team_members DROP CONSTRAINT IF EXISTS team_members_user_profile_id_fkey"
    )

    alter table(:team_members, prefix: "platform") do
      modify :team_id,
             references(:teams, column: :id, name: "team_members_team_id_fkey", type: :uuid)

      modify :user_id,
             references(:users, column: :id, name: "team_members_user_id_fkey", type: :uuid)
    end
  end

  def down do
    drop constraint(:team_members, "team_members_team_id_fkey", prefix: "platform")

    drop constraint(:team_members, "team_members_user_id_fkey", prefix: "platform")

    drop table(:team_members, prefix: "platform")

    alter table(:teams, prefix: "platform") do
      remove :updated_at
      remove :inserted_at
      remove :permissions
      remove :description
      remove :name
    end

    drop constraint(:team_scopes, "team_scopes_team_id_fkey", prefix: "platform")

    alter table(:team_scopes, prefix: "platform") do
      modify :team_id, :uuid
    end

    drop table(:teams, prefix: "platform")

    drop table(:team_scopes, prefix: "platform")
  end
end
