defmodule Mcp.Repo.Migrations.AddApiKeysFixedV2 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:api_keys, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :name, :text, null: false
      add :key_hash, :text, null: false
      add :prefix, :text, null: false
      add :last_used_at, :utc_datetime_usec
      add :reseller_id, :uuid

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :tenant_id,
          references(:tenants,
            column: :id,
            name: "api_keys_tenant_id_fkey",
            type: :uuid,
            prefix: "platform"
          )

      add :merchant_id, :uuid
    end
  end

  def down do
    drop constraint(:api_keys, "api_keys_tenant_id_fkey")

    drop constraint(:api_keys, "api_keys_merchant_id_fkey")

    drop table(:api_keys)
  end
end
