defmodule Mcp.Repo.Migrations.RefactorRiskAssessment do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:document_analyses, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :status, :text, null: false, default: "pending"
      add :markdown_content, :text
      add :structured_data, :map
      add :provider, :text, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :merchant_id, :uuid, null: false
    end

    # alter table(:users, prefix: "platform") do
    #   remove :encrypted_oauth_tokens
    #   remove :encrypted_backup_codes
    #   remove :encrypted_totp_secret
    #   add :totp_secret, :text
    #   add :backup_codes, {:array, :text}, default: []
    #   add :oauth_tokens, :map, default: %{}
    # end

    # alter table(:tenants, prefix: "platform") do
    #   add :settings, :map, default: %{}
    # end
  end

  def down do
    # alter table(:tenants, prefix: "platform") do
    #   remove :settings
    # end

    # alter table(:users, prefix: "platform") do
    #   remove :oauth_tokens
    #   remove :backup_codes
    #   remove :totp_secret
    #   add :encrypted_totp_secret, :binary
    #   add :encrypted_backup_codes, :binary
    #   add :encrypted_oauth_tokens, :binary
    # end

    drop constraint(:document_analyses, "document_analyses_merchant_id_fkey")

    drop table(:document_analyses)
  end
end
