defmodule Mcp.Repo.Migrations.AddLlmUsage do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:llm_usages, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :provider, :text, null: false
      add :model, :text, null: false
      add :prompt_tokens, :bigint, null: false, default: 0
      add :completion_tokens, :bigint, null: false, default: 0
      add :total_tokens, :bigint, null: false, default: 0
      add :cost, :decimal
      add :latency_ms, :bigint

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :execution_id,
          references(:executions,
            column: :id,
            name: "llm_usages_execution_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :tenant_id,
          references(:tenants,
            column: :id,
            name: "llm_usages_tenant_id_fkey",
            type: :uuid,
            prefix: "platform"
          )
    end
  end

  def down do
    drop constraint(:llm_usages, "llm_usages_execution_id_fkey")

    drop constraint(:llm_usages, "llm_usages_tenant_id_fkey")

    drop table(:llm_usages)
  end
end
