defmodule Mcp.Repo.Migrations.CreateWebhooks do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:webhook_deliveries) do
      modify :status, :text, default: nil
      modify :event, :text, null: true
      add :attempt_count, :bigint, default: 0
    end

    alter table(:webhook_endpoints) do
      modify :events, {:array, :text}, default: nil
      add :description, :text
    end
  end

  def down do
    alter table(:webhook_endpoints) do
      remove :description
      modify :events, {:array, :text}, default: []
    end

    alter table(:webhook_deliveries) do
      remove :attempt_count
      modify :event, :text, null: false
      modify :status, :text, default: "pending"
    end
  end
end
