defmodule Mcp.Repo.Migrations.GeneratePaymentsTables do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:payment_refunds, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :amount, :bigint, null: false
      add :currency, :text, null: false
      add :status, :text, default: "pending"
      add :provider_ref, :text
      add :reason, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :charge_id, :uuid
    end

    create table(:payment_methods, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :type, :text
      add :provider, :text, null: false
      add :provider_token, :text
      add :last4, :text
      add :brand, :text
      add :exp_month, :bigint
      add :exp_year, :bigint

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :customer_id, :uuid
    end

    create table(:payment_gateway_transactions, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :provider, :text, null: false
      add :provider_ref, :text
      add :type, :text
      add :amount, :bigint
      add :currency, :text
      add :status, :text
      add :raw_response, :map

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :charge_id, :uuid
    end

    create table(:payment_customers, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:payment_methods) do
      modify :customer_id,
             references(:payment_customers,
               column: :id,
               name: "payment_methods_customer_id_fkey",
               type: :uuid
             )
    end

    alter table(:payment_customers) do
      add :email, :text, null: false
      add :name, :text
      add :phone, :text
      add :provider_refs, :map

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create table(:payment_charges, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:payment_refunds) do
      modify :charge_id,
             references(:payment_charges,
               column: :id,
               name: "payment_refunds_charge_id_fkey",
               type: :uuid
             )
    end

    alter table(:payment_gateway_transactions) do
      modify :charge_id,
             references(:payment_charges,
               column: :id,
               name: "payment_gateway_transactions_charge_id_fkey",
               type: :uuid
             )
    end

    alter table(:payment_charges) do
      add :amount, :bigint, null: false
      add :currency, :text, null: false
      add :status, :text, default: "pending"
      add :provider, :text, null: false
      add :provider_ref, :text
      add :failure_reason, :text
      add :captured_at, :utc_datetime_usec

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :customer_id,
          references(:payment_customers,
            column: :id,
            name: "payment_charges_customer_id_fkey",
            type: :uuid
          )

      add :payment_method_id,
          references(:payment_methods,
            column: :id,
            name: "payment_charges_payment_method_id_fkey",
            type: :uuid
          )
    end
  end

  def down do
    drop constraint(:payment_charges, "payment_charges_customer_id_fkey")

    drop constraint(:payment_charges, "payment_charges_payment_method_id_fkey")

    alter table(:payment_charges) do
      remove :payment_method_id
      remove :customer_id
      remove :updated_at
      remove :inserted_at
      remove :captured_at
      remove :failure_reason
      remove :provider_ref
      remove :provider
      remove :status
      remove :currency
      remove :amount
    end

    drop constraint(:payment_gateway_transactions, "payment_gateway_transactions_charge_id_fkey")

    alter table(:payment_gateway_transactions) do
      modify :charge_id, :uuid
    end

    drop constraint(:payment_refunds, "payment_refunds_charge_id_fkey")

    alter table(:payment_refunds) do
      modify :charge_id, :uuid
    end

    drop table(:payment_charges)

    alter table(:payment_customers) do
      remove :updated_at
      remove :inserted_at
      remove :provider_refs
      remove :phone
      remove :name
      remove :email
    end

    drop constraint(:payment_methods, "payment_methods_customer_id_fkey")

    alter table(:payment_methods) do
      modify :customer_id, :uuid
    end

    drop table(:payment_customers)

    drop table(:payment_gateway_transactions)

    drop table(:payment_methods)

    drop table(:payment_refunds)
  end
end
