defmodule Mcp.Repo.Migrations.AddTransferIdToLlmUsage do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:llm_usages) do
      add :transfer_id, :uuid
    end
  end

  def down do
    alter table(:llm_usages) do
      remove :transfer_id
    end
  end
end
