defmodule Mcp.Repo.Migrations.AddChatExtensions1 do
  @moduledoc """
  Installs any extensions that are mentioned in the repo's `installed_extensions/0` callback

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    # Skip pg_partman as it's not available in the current PostgreSQL installation
    # execute("CREATE EXTENSION IF NOT EXISTS \"pg_partman\"")

    # Skip age extension as it's not available in the current PostgreSQL installation
    # execute("CREATE EXTENSION IF NOT EXISTS \"age\"")

    # Add extensions that are actually available
    execute("CREATE EXTENSION IF NOT EXISTS \"uuid-ossp\"")
    execute("CREATE EXTENSION IF NOT EXISTS \"pgcrypto\"")
  end

  def down do
    # Uncomment this if you actually want to uninstall the extensions
    # when this migration is rolled back:
    # execute("DROP EXTENSION IF EXISTS \"pg_partman\"")
    # execute("DROP EXTENSION IF EXISTS \"age\"")
  end
end
