defmodule Mcp.Repo.Migrations.AddAgenticUaasResources do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:instruction_sets, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :name, :text, null: false
      add :instructions, :text, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :blueprint_id, :uuid, null: false
      add :tenant_id, :uuid
    end

    create table(:executions, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :subject_id, :uuid, null: false
      add :subject_type, :text, null: false
      add :status, :text, null: false, default: "pending"
      add :context, :map, default: %{}
      add :results, :map, default: %{}

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :pipeline_id, :uuid, null: false
    end

    create table(:pipelines, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:executions) do
      modify :pipeline_id,
             references(:pipelines,
               column: :id,
               name: "executions_pipeline_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:pipelines) do
      add :name, :text, null: false
      add :description, :text
      add :stages, {:array, :map}, null: false, default: []

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :tenant_id,
          references(:tenants,
            column: :id,
            name: "pipelines_tenant_id_fkey",
            type: :uuid,
            prefix: "platform"
          )
    end

    create table(:agent_blueprints, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:instruction_sets) do
      modify :blueprint_id,
             references(:agent_blueprints,
               column: :id,
               name: "instruction_sets_blueprint_id_fkey",
               type: :uuid,
               prefix: "public"
             )

      modify :tenant_id,
             references(:tenants,
               column: :id,
               name: "instruction_sets_tenant_id_fkey",
               type: :uuid,
               prefix: "platform"
             )
    end

    alter table(:agent_blueprints) do
      add :name, :text, null: false
      add :description, :text
      add :base_prompt, :text, null: false
      add :tools, {:array, :text}, default: []

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end
  end

  def down do
    alter table(:agent_blueprints) do
      remove :updated_at
      remove :inserted_at
      remove :tools
      remove :base_prompt
      remove :description
      remove :name
    end

    drop constraint(:instruction_sets, "instruction_sets_blueprint_id_fkey")

    drop constraint(:instruction_sets, "instruction_sets_tenant_id_fkey")

    alter table(:instruction_sets) do
      modify :tenant_id, :uuid
      modify :blueprint_id, :uuid
    end

    drop table(:agent_blueprints)

    drop constraint(:pipelines, "pipelines_tenant_id_fkey")

    alter table(:pipelines) do
      remove :tenant_id
      remove :updated_at
      remove :inserted_at
      remove :stages
      remove :description
      remove :name
    end

    drop constraint(:executions, "executions_pipeline_id_fkey")

    alter table(:executions) do
      modify :pipeline_id, :uuid
    end

    drop table(:pipelines)

    drop table(:executions)

    drop table(:instruction_sets)
  end
end
