defmodule Mcp.Repo.Migrations.AddReviewedByToRegistrationRequests do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:registration_requests, prefix: "platform") do
      add :reviewed_by, :text
    end
  end

  def down do
    alter table(:registration_requests, prefix: "platform") do
      remove :reviewed_by
    end
  end
end
