defmodule Mcp.Repo.Migrations.CheckOverrideFix do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    execute("DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'money_with_currency') THEN CREATE TYPE money_with_currency AS (amount numeric, currency varchar(3)); END IF; END $$;")

    alter table(:balances, prefix: "finance") do
      add :balance, :money_with_currency, null: false
    end

    create unique_index(:balances, [:account_id, :transfer_id],
             name: "balances_unique_references_index",
             prefix: "finance"
           )
  end

  def down do
    drop_if_exists unique_index(:balances, [:account_id, :transfer_id],
                     name: "balances_unique_references_index",
                     prefix: "finance"
                   )

    alter table(:balances, prefix: "finance") do
      remove :balance
    end
  end
end
