defmodule Mcp.Repo.Migrations.CheckManualRelationships do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:transfers, prefix: "finance") do
      modify :updated_at, :utc_datetime_usec, null: true
    end

    alter table(:balances, prefix: "finance") do
      remove :balance
    end

    drop_if_exists unique_index(:balances, [:account_id, :transfer_id],
                     name: "balances_unique_references_index",
                     prefix: "finance"
                   )

    alter table(:balances, prefix: "finance") do
      add :transfer_id, :uuid, null: true
      modify :account_id, :uuid, null: true
    end
  end

  def down do
    alter table(:balances, prefix: "finance") do
      modify :account_id, :uuid, null: false
      modify :transfer_id, :binary, null: false
    end

    create unique_index(:balances, [:account_id, :transfer_id],
             name: "balances_unique_references_index",
             prefix: "finance"
           )

    alter table(:balances, prefix: "finance") do
      add :balance, :money_with_currency, null: false
    end

    alter table(:transfers, prefix: "finance") do
      modify :updated_at, :utc_datetime_usec, null: false
    end
  end
end
