defmodule Mcp.Repo.Migrations.SharedEntitiesUpdate do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    execute("CREATE EXTENSION IF NOT EXISTS postgis")

    alter table(:addresses, prefix: "platform") do
      add :geo_location, :geometry
    end
  end

  def down do
    alter table(:addresses, prefix: "platform") do
      remove :geo_location
    end
  end
end
