defmodule Mcp.Repo.Migrations.CreateUnderwritingDocuments do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:underwriting_documents, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :file_path, :text, null: false
      add :file_name, :text, null: false
      add :mime_type, :text, null: false
      add :document_type, :text, default: "other"
      add :status, :text, default: "pending"

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :application_id, :uuid
    end
  end

  def down do
    drop constraint(:underwriting_documents, "underwriting_documents_application_id_fkey")

    drop table(:underwriting_documents)
  end
end
