defmodule Mcp.Repo.Migrations.UnderwritingRemediationV1 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    # Already exists from 20260102000000
    #    alter table(:users, prefix: "platform") do
    #      add :merchant_id, :uuid
    #    end
  end

  def down do
    alter table(:users, prefix: "platform") do
      remove :merchant_id
    end
  end
end
