defmodule Mcp.Repo.Migrations.AddSubjectsToChat do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:conversations) do
      add :subject_id, :uuid
      add :subject_type, :text
    end

    drop_if_exists index(:documents, ["embedding vector_cosine_ops"],
                     name: "documents_embedding_index"
                   )

    alter table(:documents) do
      modify :embedding, :vector, size: 1536
    end
  end

  def down do
    alter table(:documents) do
      modify :embedding, :vector
    end

    create index(:documents, ["embedding vector_cosine_ops"],
             name: "documents_embedding_index",
             using: "hnsw"
           )

    alter table(:conversations) do
      remove :subject_type
      remove :subject_id
    end
  end
end
