defmodule Mcp.Repo.Migrations.AddProcessorAndBankProfile do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:underwriting_bank_profiles, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :name, :text, null: false
      add :appetite_rules, :map
      add :risk_weight, :bigint, default: 50
      add :is_default, :boolean, default: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :processor_id, :uuid, null: false
    end

    create table(:underwriting_processors, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:underwriting_bank_profiles) do
      modify :processor_id,
             references(:underwriting_processors,
               column: :id,
               name: "underwriting_bank_profiles_processor_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:underwriting_processors) do
      add :name, :text, null: false
      add :adapter, :text
      add :status, :text, default: "active"

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end
  end

  def down do
    alter table(:underwriting_processors) do
      remove :updated_at
      remove :inserted_at
      remove :status
      remove :adapter
      remove :name
    end

    drop constraint(:underwriting_bank_profiles, "underwriting_bank_profiles_processor_id_fkey")

    alter table(:underwriting_bank_profiles) do
      modify :processor_id, :uuid
    end

    drop table(:underwriting_processors)

    drop table(:underwriting_bank_profiles)
  end
end
