defmodule Mcp.Repo.Migrations.AddProcessorRegions do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:underwriting_processors) do
      add :supported_regions, {:array, :text}
    end
  end

  def down do
    alter table(:underwriting_processors) do
      remove :supported_regions
    end
  end
end
