defmodule Mcp.Repo.Migrations.AddAuditTrail do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:resellers_versions, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :version_action_type, :text, null: false

      add :version_source_id,
          references(:resellers,
            column: :id,
            name: "resellers_versions_version_source_id_fkey",
            type: :uuid
          ),
          null: false

      add :changes, :map

      add :version_inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :version_updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create table(:developers_versions, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :version_action_type, :text, null: false

      add :version_source_id,
          references(:developers,
            column: :id,
            name: "developers_versions_version_source_id_fkey",
            type: :uuid
          ),
          null: false

      add :changes, :map

      add :version_inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :version_updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end
  end

  def down do
    drop constraint(:developers_versions, "developers_versions_version_source_id_fkey")

    drop table(:developers_versions)

    drop constraint(:resellers_versions, "resellers_versions_version_source_id_fkey")

    drop table(:resellers_versions)
  end
end
