defmodule McpWeb.Endpoint do
  use Phoenix.Endpoint, otp_app: :mcp

  # The session will be stored in the cookie and signed,
  # this means its contents can be read but not tampered with.
  # Set :encryption_salt if you would also like to encrypt it.
  @session_options [
    store: :cookie,
    key: "_mcp_key",
    signing_salt: "ATUG2KBX",
    encryption_salt: "SOME_ENCRYPTION_SALT",
    same_site: "Lax",
    # Only send over HTTPS in production
    secure: true,
    http_only: true,
    # 30 days
    max_age: 30 * 24 * 60 * 60
  ]

  # Override with environment-specific settings if available
  @session_options Application.compile_env(:mcp, McpWeb.Endpoint, [])
                   |> Keyword.get(:session_options, @session_options)

  socket "/live", Phoenix.LiveView.Socket,
    websocket: [connect_info: [session: @session_options]],
    longpoll: [connect_info: [session: @session_options]]

  # Serve at "/" the static files from "priv/static" directory.
  #
  # When code reloading is disabled (e.g., in production),
  # the `gzip` option is enabled to serve compressed
  # static files generated by running `phx.digest`.
  plug Plug.Static,
    at: "/",
    from: :mcp,
    gzip: not code_reloading?,
    only: McpWeb.static_paths()

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    socket "/phoenix/live_reload/socket", Phoenix.LiveReloader.Socket
    plug Phoenix.LiveReloader
    plug Phoenix.CodeReloader
    plug Phoenix.Ecto.CheckRepoStatus, otp_app: :mcp
  end

  plug Phoenix.LiveDashboard.RequestLogger,
    param_key: "request_logger",
    cookie_key: "request_logger"

  plug Plug.RequestId
  plug Plug.Telemetry, event_prefix: [:phoenix, :endpoint]

  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    json_decoder: Phoenix.json_library()

  plug Plug.MethodOverride
  plug Plug.Head
  plug Plug.Session, @session_options
  plug McpWeb.TenantRouting
  plug McpWeb.TenantContext
  plug McpWeb.Router
end
